name: Default Module Test Workflow

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      rakudo-version:
        required: true
        type: string
      zef-version:
        required: false
        type: string
        default: 'v0.14.2'

jobs:
  DefaultModuleTest:
    runs-on: ${{ inputs.os }}
    defaults:
      run:
        working-directory: main
    steps:
      - uses: Raku/setup-raku@v1
        name: Prepare Rakudo ${{ inputs.rakudo-version }} environment
        with:
          raku-version: ${{ inputs.rakudo-version }}
      - uses: actions/checkout@v3
        name: Checkout zef
        with:
          repository: 'ugexe/zef'
          ref: ${{ inputs.zef-version }}
          path: 'zef'
      - uses: nick-fields/retry@v2
        name: Install new zef ${{ inputs.zef-version }}
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: raku -I./zef zef/bin/zef install ./zef
      - uses: actions/checkout@v3
        name: Checkout repository
        with:
          submodules: recursive
          path: 'main'
      - name: Versions Report
        run: |
          raku -v
          zef --version
      - uses: nick-fields/retry@v2
        name: Setup dependencies
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: zef install ./main --deps-only --test-depends --/test
      - uses: nick-fields/retry@v2
        name: Setup App::Prove6
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: zef install --/test App::Prove6
      - name: Run tests
        run: prove6 -I. --verbose --err=stderr

      # add commands below for your own requirements
