name: Default Module Test Workflow

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      rakudo-version:
        required: true
        type: string

jobs:
  DefaultModuleTest:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: Raku/setup-raku@v1
        name: Prepare Rakudo ${{ inputs.rakudo-version }} environment
        with:
          raku-version: ${{ inputs.rakudo-version }}
      - uses: actions/checkout@v3
        name: Checkout zef
        with:
          repository: 'ugexe/zef'
          ref: 'v0.14.2'
          path: 'zef'
      - run: |
          pwd
      - uses: actions/checkout@v3
        name: Checkout repository
        with:
          submodules: recursive
      - run: |
          raku -v
          zef --version
          pwd
        name: Versions Report
      - run: |
          zef install . --deps-only --test-depends --/test
          zef install --/test App::Prove6
          prove6 -I. --verbose
        name: Run tests

      # add commands below for your own requirements
